-- Add new columns to users table if they don't exist
ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS address TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS state VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS pincode VARCHAR(10) DEFAULT NULL;
